coding_task:
  description: >
    Write terraform code to achieve this: {assignment}
  expected_output: >
    A text file that includes the code itself.
  agent: coder
  output_file: output/code_and_output.txt